#!/bin/bash
URL="http://localhost:8080"
[ "$1" = "-o" ] && URL="https://split-isdc.kuchta.dev"
CONTENT_TYPE_HEADER="Content-Type: application/json"       

# Function to make POST requests
function curl_post() {
    local path="$1"
    local data="$2"
    local auth_header="$3"
    echo -e "\n\033[32;1m$URL$path\033[0m"
    if [ -n "$auth_header" ]; then
        curl -i -X POST "$URL$path" -H "$CONTENT_TYPE_HEADER" -H "$auth_header" --data "$data"
    else
        curl -i -X POST "$URL$path" -H "$CONTENT_TYPE_HEADER" --data "$data"
    fi

}

# First batch
curl_post "/register" '{"username":"isdc", "password":"isdc"}'
curl_post "/register" '{"username":"another", "password":"another"}'
curl_post "/register" '{"username":"yet", "password":"yet"}'
# Get the token for user "isdc"
AUTH_HEADER="Authorization: Bearer $(curl -s -X POST "$URL/login" -H "$CONTENT_TYPE_HEADER" --data-raw '{"username":"isdc", "password":"isdc"}' | jq -r .token)"
echo "$AUTH_HEADER"

# Create a new group and add members and items
curl_post "/groups" '{"name":"Home Group"}' "$AUTH_HEADER"
curl_post "/groups/1/members" '{"member_id":1}' "$AUTH_HEADER"
curl_post "/groups/1/members" '{"member_id":2}' "$AUTH_HEADER"
curl_post "/groups/1/members" '{"member_id":3}' "$AUTH_HEADER"

# Items for group 1
timestamp=$(date +%s)

# group_id will be ignored because the group it really gets added to is defined with path params
curl_post "/groups/1/items" "{\"id\":0, \"name\":\"eggs\", \"price\":12.12, \"author_id\":1, \"group_id\":0, \"timestamp\":$timestamp}" "$AUTH_HEADER"
curl_post "/groups/1/items" "{\"id\":0, \"name\":\"art\", \"price\":5.65, \"author_id\":1, \"group_id\":0, \"timestamp\":$timestamp}" "$AUTH_HEADER"
curl_post "/groups/1/items" "{\"id\":0, \"name\":\"mice\", \"price\":9.65, \"author_id\":2,\"group_id\":0,  \"timestamp\":$timestamp}" "$AUTH_HEADER"

# Second batch
curl_post "/register" '{"username":"jan", "password":"jan"}'
curl_post "/register" '{"username":"alek", "password":"alek"}'
curl_post "/register" '{"username":"maksim", "password":"maksim"}'

# Get the token for user "jan"
AUTH_HEADER="Authorization: Bearer $(curl -s -X POST "$URL/login" -H "$CONTENT_TYPE_HEADER" --data-raw '{"username":"jan", "password":"jan"}' | jq -r .token)"

curl_post "/groups" '{"name":"Hideout"}' "$AUTH_HEADER"
curl_post "/groups/2/members" '{"member_id":4}' "$AUTH_HEADER"
curl_post "/groups/2/members" '{"member_id":5}' "$AUTH_HEADER"
curl_post "/groups/2/members" '{"member_id":6}' "$AUTH_HEADER"

# Items for group 2
timestamp=$(date +%s)
curl_post "/groups/2/items" "{\"id\":0,\"name\":\"mayo\", \"price\":48.12, \"author_id\":4, \"group_id\":0, \"timestamp\":$timestamp}" "$AUTH_HEADER"
curl_post "/groups/2/items" "{\"id\":0,\"name\":\"laptop\", \"price\":59.65, \"author_id\":5, \"group_id\":0, \"timestamp\":$timestamp}" "$AUTH_HEADER"
curl_post "/groups/2/items" "{\"id\":0,\"name\":\"pc\", \"price\":339.65, \"author_id\":4, \"group_id\":0, \"timestamp\":$timestamp}" "$AUTH_HEADER"
