//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Items struct {
	ID        int32 `sql:"primary_key"`
	Timestamp int32
	Name      string
	Price     float32
	AuthorID  int32
	GroupID   int32
}
